import type { Admission } from "@/types"

export const mockAdmissions: Admission[] = [
  {
    id: "ADM-2024-001",
    admission_date: "2024-01-15",
    discharge_date: "2024-01-22",
    province: "Madrid",
    municipality: "Madrid",
    sex: "Masculino",
    age_group: "26-40",
    primary_diagnosis_code: "F32.1",
    diagnosis_chapter: "F30-F39: Trastornos del humor",
    length_of_stay: 7,
    readmission_30d: false,
    severity_score: 6,
  },
  {
    id: "ADM-2024-002",
    admission_date: "2024-01-18",
    discharge_date: "2024-02-05",
    province: "Barcelona",
    municipality: "Barcelona",
    sex: "Femenino",
    age_group: "18-25",
    primary_diagnosis_code: "F20.0",
    diagnosis_chapter: "F20-F29: Esquizofrenia y trastornos psicóticos",
    length_of_stay: 18,
    readmission_30d: true,
    severity_score: 8,
  },
  {
    id: "ADM-2024-003",
    admission_date: "2024-01-20",
    discharge_date: "2024-01-25",
    province: "Valencia",
    municipality: "Valencia",
    sex: "Masculino",
    age_group: "41-65",
    primary_diagnosis_code: "F10.2",
    diagnosis_chapter: "F10-F19: Trastornos por uso de sustancias",
    length_of_stay: 5,
    readmission_30d: false,
    severity_score: 5,
  },
  {
    id: "ADM-2024-004",
    admission_date: "2024-02-01",
    discharge_date: "2024-02-14",
    province: "Sevilla",
    municipality: "Sevilla",
    sex: "Femenino",
    age_group: "26-40",
    primary_diagnosis_code: "F41.1",
    diagnosis_chapter: "F40-F48: Trastornos de ansiedad",
    length_of_stay: 13,
    readmission_30d: false,
    severity_score: 7,
  },
  {
    id: "ADM-2024-005",
    admission_date: "2024-02-05",
    discharge_date: "2024-02-12",
    province: "Madrid",
    municipality: "Alcalá de Henares",
    sex: "Masculino",
    age_group: "18-25",
    primary_diagnosis_code: "F50.0",
    diagnosis_chapter: "F50-F59: Trastornos de la conducta alimentaria",
    length_of_stay: 7,
    readmission_30d: false,
    severity_score: 6,
  },
  {
    id: "ADM-2024-006",
    admission_date: "2024-02-10",
    discharge_date: "2024-02-28",
    province: "Zaragoza",
    municipality: "Zaragoza",
    sex: "Femenino",
    age_group: "66+",
    primary_diagnosis_code: "F03",
    diagnosis_chapter: "F00-F09: Trastornos mentales orgánicos",
    length_of_stay: 18,
    readmission_30d: true,
    severity_score: 9,
  },
  {
    id: "ADM-2024-007",
    admission_date: "2024-02-15",
    discharge_date: "2024-02-20",
    province: "Málaga",
    municipality: "Málaga",
    sex: "Masculino",
    age_group: "26-40",
    primary_diagnosis_code: "F60.3",
    diagnosis_chapter: "F60-F69: Trastornos de la personalidad",
    length_of_stay: 5,
    readmission_30d: false,
    severity_score: 4,
  },
  {
    id: "ADM-2024-008",
    admission_date: "2024-03-01",
    discharge_date: "2024-03-15",
    province: "Barcelona",
    municipality: "Hospitalet de Llobregat",
    sex: "Femenino",
    age_group: "41-65",
    primary_diagnosis_code: "F33.2",
    diagnosis_chapter: "F30-F39: Trastornos del humor",
    length_of_stay: 14,
    readmission_30d: false,
    severity_score: 7,
  },
  {
    id: "ADM-2024-009",
    admission_date: "2024-03-05",
    discharge_date: "2024-03-10",
    province: "Murcia",
    municipality: "Murcia",
    sex: "Masculino",
    age_group: "18-25",
    primary_diagnosis_code: "F90.0",
    diagnosis_chapter: "F90-F98: Trastornos del comportamiento",
    length_of_stay: 5,
    readmission_30d: false,
    severity_score: 5,
  },
  {
    id: "ADM-2024-010",
    admission_date: "2024-03-10",
    discharge_date: "2024-03-25",
    province: "Palma",
    municipality: "Palma de Mallorca",
    sex: "Femenino",
    age_group: "26-40",
    primary_diagnosis_code: "F31.1",
    diagnosis_chapter: "F30-F39: Trastornos del humor",
    length_of_stay: 15,
    readmission_30d: true,
    severity_score: 8,
  },
  {
    id: "ADM-2024-011",
    admission_date: "2024-03-15",
    discharge_date: "2024-03-22",
    province: "Las Palmas",
    municipality: "Las Palmas de Gran Canaria",
    sex: "Masculino",
    age_group: "41-65",
    primary_diagnosis_code: "F10.2",
    diagnosis_chapter: "F10-F19: Trastornos por uso de sustancias",
    length_of_stay: 7,
    readmission_30d: false,
    severity_score: 6,
  },
  {
    id: "ADM-2024-012",
    admission_date: "2024-04-01",
    discharge_date: "2024-04-08",
    province: "Bilbao",
    municipality: "Bilbao",
    sex: "Femenino",
    age_group: "18-25",
    primary_diagnosis_code: "F40.1",
    diagnosis_chapter: "F40-F48: Trastornos de ansiedad",
    length_of_stay: 7,
    readmission_30d: false,
    severity_score: 5,
  },
  {
    id: "ADM-2024-013",
    admission_date: "2024-04-05",
    discharge_date: "2024-04-20",
    province: "Madrid",
    municipality: "Getafe",
    sex: "Masculino",
    age_group: "26-40",
    primary_diagnosis_code: "F20.5",
    diagnosis_chapter: "F20-F29: Esquizofrenia y trastornos psicóticos",
    length_of_stay: 15,
    readmission_30d: false,
    severity_score: 8,
  },
  {
    id: "ADM-2024-014",
    admission_date: "2024-04-10",
    discharge_date: "2024-04-17",
    province: "Valencia",
    municipality: "Gandía",
    sex: "Femenino",
    age_group: "66+",
    primary_diagnosis_code: "F05",
    diagnosis_chapter: "F00-F09: Trastornos mentales orgánicos",
    length_of_stay: 7,
    readmission_30d: false,
    severity_score: 7,
  },
  {
    id: "ADM-2024-015",
    admission_date: "2024-04-15",
    discharge_date: "2024-04-30",
    province: "Sevilla",
    municipality: "Dos Hermanas",
    sex: "Masculino",
    age_group: "41-65",
    primary_diagnosis_code: "F32.2",
    diagnosis_chapter: "F30-F39: Trastornos del humor",
    length_of_stay: 15,
    readmission_30d: true,
    severity_score: 8,
  },
  {
    id: "ADM-2024-016",
    admission_date: "2024-05-01",
    discharge_date: "2024-05-08",
    province: "Barcelona",
    municipality: "Badalona",
    sex: "Femenino",
    age_group: "18-25",
    primary_diagnosis_code: "F50.2",
    diagnosis_chapter: "F50-F59: Trastornos de la conducta alimentaria",
    length_of_stay: 7,
    readmission_30d: false,
    severity_score: 6,
  },
  {
    id: "ADM-2024-017",
    admission_date: "2024-05-05",
    discharge_date: "2024-05-12",
    province: "Zaragoza",
    municipality: "Zaragoza",
    sex: "Masculino",
    age_group: "26-40",
    primary_diagnosis_code: "F19.2",
    diagnosis_chapter: "F10-F19: Trastornos por uso de sustancias",
    length_of_stay: 7,
    readmission_30d: false,
    severity_score: 6,
  },
  {
    id: "ADM-2024-018",
    admission_date: "2024-05-10",
    discharge_date: "2024-05-25",
    province: "Málaga",
    municipality: "Marbella",
    sex: "Femenino",
    age_group: "41-65",
    primary_diagnosis_code: "F43.1",
    diagnosis_chapter: "F40-F48: Trastornos de ansiedad",
    length_of_stay: 15,
    readmission_30d: false,
    severity_score: 7,
  },
  {
    id: "ADM-2024-019",
    admission_date: "2024-05-15",
    discharge_date: "2024-05-22",
    province: "Murcia",
    municipality: "Cartagena",
    sex: "Masculino",
    age_group: "18-25",
    primary_diagnosis_code: "F91.1",
    diagnosis_chapter: "F90-F98: Trastornos del comportamiento",
    length_of_stay: 7,
    readmission_30d: false,
    severity_score: 5,
  },
  {
    id: "ADM-2024-020",
    admission_date: "2024-06-01",
    discharge_date: "2024-06-15",
    province: "Madrid",
    municipality: "Madrid",
    sex: "Femenino",
    age_group: "26-40",
    primary_diagnosis_code: "F31.2",
    diagnosis_chapter: "F30-F39: Trastornos del humor",
    length_of_stay: 14,
    readmission_30d: false,
    severity_score: 7,
  },
]
